apiVersion: apps/v1
kind: Deployment
metadata:
  name: commoncrawl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commoncrawl
  template:
    metadata:
      labels:
        app: commoncrawl
    spec:
      containers:
      - name: commoncrawl
        image: commoncrawl-worker:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: commoncrawl
spec:
  selector:
    app: commoncrawl
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
